export const LOADINGANDERROR_ISLOADING_SETTER =
  "LOADINGANDERROR_ISLOADING_SETTER";
export const LOADINGANDERROR_ERROR_SETTER = "LOADINGANDERROR_ERROR_SETTER";
export const LOADINGANDERROR_RESET_STATE = "LOADINGANDERROR_RESET_STATE";
